### ISSUE TITLE
Home screen

### ISSUE THREAD

**Issue by dishaRX** [RxMobile-Dummy/react-music-itunes#16]
- Create a home page with bottom navigation bar which should contain three tabs 

1. music
2.  podcast 
3. settings

On selecting music user will be redirected to music screen, on selecting podcast user will be redirected to podcast screen , on selecting setting user will be redirected to setting screen.

**Comment by radixdt2532** [comment]
Create a home page with bottom navigation bar which should contain three tabs - Done
music - Done
podcast - Done
settings - Done
On selecting music user will be redirected to music screen, on selecting podcast user will be redirected to podcast screen , on selecting setting user will be redirected to setting screen. - Done
